image: alpine/edge
packages:
  - podman
secrets:
  - d45b9b20-bc8b-480e-8e6e-edb5e0fd5848 # podman auth
tasks:
  - setup: |
      sudo rc-service cgroups start
      sudo modprobe tun
      sudo chmod o+rw /dev/net/tun
      echo build:100000:65536 | sudo tee /etc/subuid
      echo build:100000:65536 | sudo tee /etc/subgid
  - build: |
      podman build sparkles/ -t ghcr.io/xdavidwu/sparkles:latest
  - build-kubectl-shell: |
      podman run -v .:/work cgr.dev/chainguard/apko:latest \
        build /work/sparkles/kubectl-shell.apko.yaml kubectl-shell \
        /work/kubectl-shell.tar
      podman load -i kubectl-shell.tar
  - publish: |
      if [ "$GIT_REF" != refs/heads/main ]; then
        printf 'Skipping push on ref %s\n' "$GIT_REF"
      else
        podman push ghcr.io/xdavidwu/sparkles:latest
        podman push kubectl-shell:latest-amd64 \
          ghcr.io/xdavidwu/sparkles/kubectl-shell:latest
      fi
